#!/bin/bash
echo .
echo .
echo ==================================================
echo ===== Building Shutdown Timer ====================
echo ==================================================
echo .
if [ ! -d build ]
then
	#not configured, we have to run cmake
	mkdir build
	cd build
	cmake -G "Unix Makefiles" ..
else
        cd build
fi

make

echo ===== Build Completed ============================
echo .           
